# Generated by Django 4.2 on 2023-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_img_menu_imgage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='imgage',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
