# Generated by Django 4.2 on 2023-04-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_menu_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='imgage',
            new_name='img',
        ),
    ]
