# Generated by Django 4.2 on 2023-04-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='commit',
            new_name='comment',
        ),
    ]
